services:
  - type: web
    name: visual-product-matcher
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --chdir app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true
